name="Triska Reloaded"

[store]
id="com.github.adbenitez.Triska"
version_name=1.0
version_code=3
author="adbenitez"
author_email="adbenitez@nauta.cu"
description="Jump high and collect the lucky clovers!"